version: '3.7'

services:
  specs:
    build:
      context: .
    command: 'rake specs:all'
    working_dir: /gem_source/
    volumes:
    - .:/gem_source/

  infra:
    init: true
    image: 644358627301.dkr.ecr.ap-southeast-2.amazonaws.com/oculo/infrastructure_sceptre:latest
    volumes:
    - ./infrastructure/:/sceptre
    working_dir: /sceptre
    command: >
      sh -c "merge-cfn-templates --cfn_templates_directory /sceptre/templates &&
      sceptre launch shared --yes"
    environment:
      AWS_SESSION_TOKEN:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
