---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DomainName:
    Type: String
    Description: Hosted Zone DNS name, e.g. oculo.com.au
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
    Default: rubygems.oculo.io

Resources:
  GemsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: oculo-rubygems
      VersioningConfiguration:
        Status: Enabled
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  GemsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GemsBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Sub "arn:aws:s3:::${GemsBucket}/*"

  GemsSiteCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - GemsBucket
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Select [ 2, !Split [ "/", !GetAtt GemsBucket.WebsiteURL ] ]
          Id: S3Origin
          CustomOriginConfig:
            HTTPPort: '80'
            HTTPSPort: '443'
            OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
        - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # Managed-CachingDisabled
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref GemsSiteCertificate
          SslSupportMethod: "sni-only"

  GemsSiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Sub "${DomainName}."
      HostedZoneConfig:
        Comment: Hosted zone in the shared account for oculo.io

  GemsSiteDNSName:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # Hardcoded zone for Cloudfront distributions
        DNSName: !GetAtt GemsSiteCloudfront.DomainName
